/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use reqwest;
use serde::{Deserialize, Serialize};
use crate::{models, utils,apis::ResponseContent};
use super::{Error, configuration};


/// struct for typed errors of method [`create_ai_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateAiApiKeyError {
    Status403(models::ForbiddenOperationResponse),
    Status404(models::ErrorResponse),
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`delete_ai_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAiApiKeyError {
    Status403(models::ForbiddenOperationResponse),
    Status404(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`get_ai_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAiApiKeyError {
    Status403(models::ForbiddenOperationResponse),
    Status404(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`list_ai_api_keys`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListAiApiKeysError {
    Status403(models::ForbiddenOperationResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`rotate_ai_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RotateAiApiKeyError {
    Status403(models::ForbiddenOperationResponse),
    Status404(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`update_ai_api_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateAiApiKeyError {
    Status403(models::ForbiddenOperationResponse),
    Status404(models::ErrorResponse),
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


pub async fn create_ai_api_key(configuration: &configuration::Configuration, create_ai_api_key_request: models::CreateAiApiKeyRequest) -> Result<models::AiApiKeyWithValue, Error<CreateAiApiKeyError>> {
    let local_var_create_ai_api_key_request = create_ai_api_key_request;

    let path_params_map = std::collections::HashMap::new();

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_create_ai_api_key_request);

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/ai/ai-api-key",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn delete_ai_api_key(configuration: &configuration::Configuration, id: String) -> Result<models::DeleteAiApiKey200Response, Error<DeleteAiApiKeyError>> {
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::DELETE,
    "/ai/ai-api-key/{id}",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn get_ai_api_key(configuration: &configuration::Configuration, id: String) -> Result<models::AiApiKey, Error<GetAiApiKeyError>> {
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::GET,
    "/ai/ai-api-key/{id}",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn list_ai_api_keys(configuration: &configuration::Configuration, ) -> Result<models::ListAiApiKeysResponse, Error<ListAiApiKeysError>> {

    let path_params_map = std::collections::HashMap::new();

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::GET,
    "/ai/ai-api-key",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn rotate_ai_api_key(configuration: &configuration::Configuration, id: String) -> Result<models::AiApiKeyWithValue, Error<RotateAiApiKeyError>> {
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/ai/ai-api-key/{id}/rotate",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn update_ai_api_key(configuration: &configuration::Configuration, id: String, update_ai_api_key_request: models::UpdateAiApiKeyRequest) -> Result<models::AiApiKey, Error<UpdateAiApiKeyError>> {
    let local_var_id = id;
    let local_var_update_ai_api_key_request = update_ai_api_key_request;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_update_ai_api_key_request);

    utils::execute_request(
    configuration,
    reqwest::Method::PATCH,
    "/ai/ai-api-key/{id}",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
