/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use std::time::Duration;

use reqwest;

#[derive(Debug, Clone)]
pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: reqwest::Client,
    pub api_key: String,
    pub api_secret: String,
    pub expiration: Duration,
}

impl Configuration {
    pub fn new() -> Configuration {
        Configuration::default()
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: "https://api-ch-gva-2.exoscale.com/v2".to_owned(),
            user_agent: Some("OpenAPI-Generator/2.0.0/rust".to_owned()),
            client: reqwest::Client::new(),
            api_key: "".into(),
            api_secret: "".into(),
            expiration: Duration::from_secs(600),
        }
    }
}
