/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use reqwest;
use serde::{Deserialize, Serialize};
use crate::{models, utils,apis::ResponseContent};
use super::{Error, configuration};


/// struct for typed errors of method [`cancel_kms_key_deletion`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CancelKmsKeyDeletionError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`create_kms_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateKmsKeyError {
    Status400(models::ErrorResponse),
    Status409(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`disable_kms_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisableKmsKeyError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`disable_kms_key_rotation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisableKmsKeyRotationError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`enable_kms_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnableKmsKeyError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`enable_kms_key_rotation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnableKmsKeyRotationError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`get_kms_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetKmsKeyError {
    Status400(models::ErrorResponse),
    Status404(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`list_kms_key_rotations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListKmsKeyRotationsError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`list_kms_keys`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListKmsKeysError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`replicate_kms_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReplicateKmsKeyError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`rotate_kms_key`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RotateKmsKeyError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`schedule_kms_key_deletion`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScheduleKmsKeyDeletionError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


pub async fn cancel_kms_key_deletion(configuration: &configuration::Configuration, id: String) -> Result<models::SuccessResponse, Error<CancelKmsKeyDeletionError>> {
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/kms-key/{id}/cancel-deletion",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn create_kms_key(configuration: &configuration::Configuration, create_kms_key_request: models::CreateKmsKeyRequest) -> Result<models::CreateKmsKeyResponse, Error<CreateKmsKeyError>> {
    let local_var_create_kms_key_request = create_kms_key_request;

    let path_params_map = std::collections::HashMap::new();

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_create_kms_key_request);

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/kms-key",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn disable_kms_key(configuration: &configuration::Configuration, id: String) -> Result<models::SuccessResponse, Error<DisableKmsKeyError>> {
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/kms-key/{id}/disable",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn disable_kms_key_rotation(configuration: &configuration::Configuration, id: String) -> Result<models::DisableKmsKeyRotationResponse, Error<DisableKmsKeyRotationError>> {
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/kms-key/{id}/disable-key-rotation",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn enable_kms_key(configuration: &configuration::Configuration, id: String) -> Result<models::SuccessResponse, Error<EnableKmsKeyError>> {
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/kms-key/{id}/enable",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn enable_kms_key_rotation(configuration: &configuration::Configuration, id: String, enable_kms_key_rotation_request: models::EnableKmsKeyRotationRequest) -> Result<models::EnableKmsKeyRotationResponse, Error<EnableKmsKeyRotationError>> {
    let local_var_id = id;
    let local_var_enable_kms_key_rotation_request = enable_kms_key_rotation_request;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_enable_kms_key_rotation_request);

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/kms-key/{id}/enable-key-rotation",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn get_kms_key(configuration: &configuration::Configuration, id: String) -> Result<models::GetKmsKeyResponse, Error<GetKmsKeyError>> {
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::GET,
    "/kms-key/{id}",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn list_kms_key_rotations(configuration: &configuration::Configuration, id: String) -> Result<models::ListKmsKeyRotationsResponse, Error<ListKmsKeyRotationsError>> {
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::GET,
    "/kms-key/{id}/list-key-rotations",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn list_kms_keys(configuration: &configuration::Configuration, ) -> Result<models::ListKmsKeysResponse, Error<ListKmsKeysError>> {

    let path_params_map = std::collections::HashMap::new();

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::GET,
    "/kms-key",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn replicate_kms_key(configuration: &configuration::Configuration, id: String, replicate_kms_key_request: models::ReplicateKmsKeyRequest) -> Result<models::SuccessResponse, Error<ReplicateKmsKeyError>> {
    let local_var_id = id;
    let local_var_replicate_kms_key_request = replicate_kms_key_request;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_replicate_kms_key_request);

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/kms-key/{id}/replicate",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn rotate_kms_key(configuration: &configuration::Configuration, id: String) -> Result<models::RotateKmsKeyResponse, Error<RotateKmsKeyError>> {
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/kms-key/{id}/rotate",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn schedule_kms_key_deletion(configuration: &configuration::Configuration, id: String, schedule_kms_key_deletion_request: models::ScheduleKmsKeyDeletionRequest) -> Result<models::SuccessResponse, Error<ScheduleKmsKeyDeletionError>> {
    let local_var_id = id;
    let local_var_schedule_kms_key_deletion_request = schedule_kms_key_deletion_request;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_schedule_kms_key_deletion_request);

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/kms-key/{id}/schedule-deletion",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
