/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use reqwest;
use serde::{Deserialize, Serialize};
use crate::{models, utils,apis::ResponseContent};
use super::{Error, configuration};


/// struct for typed errors of method [`create_sks_nodepool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateSksNodepoolError {
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`delete_sks_nodepool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteSksNodepoolError {
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`evict_sks_nodepool_members`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EvictSksNodepoolMembersError {
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`get_sks_nodepool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSksNodepoolError {
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`scale_sks_nodepool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScaleSksNodepoolError {
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`update_sks_nodepool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateSksNodepoolError {
    UnknownValue(serde_json::Value),
}


pub async fn create_sks_nodepool(configuration: &configuration::Configuration, id: String, create_sks_nodepool_request: models::CreateSksNodepoolRequest) -> Result<models::Operation, Error<CreateSksNodepoolError>> {
    let local_var_id = id;
    let local_var_create_sks_nodepool_request = create_sks_nodepool_request;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_create_sks_nodepool_request);

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/sks-cluster/{id}/nodepool",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn delete_sks_nodepool(configuration: &configuration::Configuration, id: String, sks_nodepool_id: String) -> Result<models::Operation, Error<DeleteSksNodepoolError>> {
    let local_var_id = id;
    let local_var_sks_nodepool_id = sks_nodepool_id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));
                path_params_map.insert("sks_nodepool_id".to_string(), crate::apis::urlencode(local_var_sks_nodepool_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::DELETE,
    "/sks-cluster/{id}/nodepool/{sks_nodepool_id}",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn evict_sks_nodepool_members(configuration: &configuration::Configuration, id: String, sks_nodepool_id: String, evict_sks_nodepool_members_request: models::EvictSksNodepoolMembersRequest) -> Result<models::Operation, Error<EvictSksNodepoolMembersError>> {
    let local_var_id = id;
    let local_var_sks_nodepool_id = sks_nodepool_id;
    let local_var_evict_sks_nodepool_members_request = evict_sks_nodepool_members_request;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));
                path_params_map.insert("sks_nodepool_id".to_string(), crate::apis::urlencode(local_var_sks_nodepool_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_evict_sks_nodepool_members_request);

    utils::execute_request(
    configuration,
    reqwest::Method::PUT,
    "/sks-cluster/{id}/nodepool/{sks_nodepool_id}:evict",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn get_sks_nodepool(configuration: &configuration::Configuration, id: String, sks_nodepool_id: String) -> Result<models::SksNodepool, Error<GetSksNodepoolError>> {
    let local_var_id = id;
    let local_var_sks_nodepool_id = sks_nodepool_id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));
                path_params_map.insert("sks_nodepool_id".to_string(), crate::apis::urlencode(local_var_sks_nodepool_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::GET,
    "/sks-cluster/{id}/nodepool/{sks_nodepool_id}",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn scale_sks_nodepool(configuration: &configuration::Configuration, id: String, sks_nodepool_id: String, scale_sks_nodepool_request: models::ScaleSksNodepoolRequest) -> Result<models::Operation, Error<ScaleSksNodepoolError>> {
    let local_var_id = id;
    let local_var_sks_nodepool_id = sks_nodepool_id;
    let local_var_scale_sks_nodepool_request = scale_sks_nodepool_request;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));
                path_params_map.insert("sks_nodepool_id".to_string(), crate::apis::urlencode(local_var_sks_nodepool_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_scale_sks_nodepool_request);

    utils::execute_request(
    configuration,
    reqwest::Method::PUT,
    "/sks-cluster/{id}/nodepool/{sks_nodepool_id}:scale",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn update_sks_nodepool(configuration: &configuration::Configuration, id: String, sks_nodepool_id: String, update_sks_nodepool_request: models::UpdateSksNodepoolRequest) -> Result<models::Operation, Error<UpdateSksNodepoolError>> {
    let local_var_id = id;
    let local_var_sks_nodepool_id = sks_nodepool_id;
    let local_var_update_sks_nodepool_request = update_sks_nodepool_request;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));
                path_params_map.insert("sks_nodepool_id".to_string(), crate::apis::urlencode(local_var_sks_nodepool_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_update_sks_nodepool_request);

    utils::execute_request(
    configuration,
    reqwest::Method::PUT,
    "/sks-cluster/{id}/nodepool/{sks_nodepool_id}",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
