/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use reqwest;
use serde::{Deserialize, Serialize};
use crate::{models, utils,apis::ResponseContent};
use super::{Error, configuration};


/// struct for typed errors of method [`get_iam_organization_policy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIamOrganizationPolicyError {
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`reset_iam_organization_policy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ResetIamOrganizationPolicyError {
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`update_iam_organization_policy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateIamOrganizationPolicyError {
    UnknownValue(serde_json::Value),
}


pub async fn get_iam_organization_policy(configuration: &configuration::Configuration, ) -> Result<models::IamPolicy, Error<GetIamOrganizationPolicyError>> {

    let path_params_map = std::collections::HashMap::new();

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::GET,
    "/iam-organization-policy",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn reset_iam_organization_policy(configuration: &configuration::Configuration, ) -> Result<models::Operation, Error<ResetIamOrganizationPolicyError>> {

    let path_params_map = std::collections::HashMap::new();

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/iam-organization-policy:reset",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn update_iam_organization_policy(configuration: &configuration::Configuration, iam_policy: models::IamPolicy) -> Result<models::Operation, Error<UpdateIamOrganizationPolicyError>> {
    let local_var_iam_policy = iam_policy;

    let path_params_map = std::collections::HashMap::new();

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_iam_policy);

    utils::execute_request(
    configuration,
    reqwest::Method::PUT,
    "/iam-organization-policy",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
