/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use reqwest;
use serde::{Deserialize, Serialize};
use crate::{models, utils,apis::ResponseContent};
use super::{Error, configuration};


/// struct for typed errors of method [`create_route`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRouteError {
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`delete_route`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteRouteError {
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`list_routes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListRoutesError {
    UnknownValue(serde_json::Value),
}


/// struct for typed errors of method [`list_vpc_routes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListVpcRoutesError {
    UnknownValue(serde_json::Value),
}


pub async fn create_route(configuration: &configuration::Configuration, vpc_id: String, subnet_id: String, create_route_request: models::CreateRouteRequest) -> Result<models::Route, Error<CreateRouteError>> {
    let local_var_vpc_id = vpc_id;
    let local_var_subnet_id = subnet_id;
    let local_var_create_route_request = create_route_request;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("vpc_id".to_string(), crate::apis::urlencode(local_var_vpc_id));
                path_params_map.insert("subnet_id".to_string(), crate::apis::urlencode(local_var_subnet_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
            let body_payload_option = Some(local_var_create_route_request);

    utils::execute_request(
    configuration,
    reqwest::Method::POST,
    "/vpc/{vpc_id}/subnet/{subnet_id}/route",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn delete_route(configuration: &configuration::Configuration, vpc_id: String, subnet_id: String, id: String) -> Result<serde_json::Value, Error<DeleteRouteError>> {
    let local_var_vpc_id = vpc_id;
    let local_var_subnet_id = subnet_id;
    let local_var_id = id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("vpc_id".to_string(), crate::apis::urlencode(local_var_vpc_id));
                path_params_map.insert("subnet_id".to_string(), crate::apis::urlencode(local_var_subnet_id));
                path_params_map.insert("id".to_string(), crate::apis::urlencode(local_var_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::DELETE,
    "/vpc/{vpc_id}/subnet/{subnet_id}/route/{id}",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn list_routes(configuration: &configuration::Configuration, vpc_id: String, subnet_id: String) -> Result<models::ListVpcRoutes200Response, Error<ListRoutesError>> {
    let local_var_vpc_id = vpc_id;
    let local_var_subnet_id = subnet_id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("vpc_id".to_string(), crate::apis::urlencode(local_var_vpc_id));
                path_params_map.insert("subnet_id".to_string(), crate::apis::urlencode(local_var_subnet_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::GET,
    "/vpc/{vpc_id}/subnet/{subnet_id}/route",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
pub async fn list_vpc_routes(configuration: &configuration::Configuration, vpc_id: String) -> Result<models::ListVpcRoutes200Response, Error<ListVpcRoutesError>> {
    let local_var_vpc_id = vpc_id;

    let mut path_params_map = std::collections::HashMap::new();
                path_params_map.insert("vpc_id".to_string(), crate::apis::urlencode(local_var_vpc_id));

    let query_params_vec: Vec<(&str, String)> = Vec::new();
    let query_params_option = if query_params_vec.is_empty() { None } else { Some(query_params_vec.as_slice())};
        let body_payload_option: Option<()> = None;

    utils::execute_request(
    configuration,
    reqwest::Method::GET,
    "/vpc/{vpc_id}/route",
    path_params_map,
    query_params_option,
    body_payload_option,
    ).await
}
