/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutovacuumSettings {
    /// Causes each action executed by autovacuum to be logged if it ran for at least the specified number of milliseconds. Setting this to zero logs all autovacuum actions. Minus-one disables logging autovacuum actions. The default is `1000`.
    #[serde(rename = "log_autovacuum_min_duration", skip_serializing_if = "Option::is_none")]
    pub log_autovacuum_min_duration: Option<i32>,
    /// Specifies the cost limit value that will be used in automatic VACUUM operations. If `-1` is specified, the regular vacuum_cost_limit value will be used. The default is `-1` (upstream default).
    #[serde(rename = "autovacuum_vacuum_cost_limit", skip_serializing_if = "Option::is_none")]
    pub autovacuum_vacuum_cost_limit: Option<i16>,
    /// Specifies the maximum number of autovacuum processes (other than the autovacuum launcher) that may be running at any one time. The default is `3`. Changing this parameter causes a service restart.
    #[serde(rename = "autovacuum_max_workers", skip_serializing_if = "Option::is_none")]
    pub autovacuum_max_workers: Option<u8>,
    /// Specifies the minimum number of updated or deleted tuples needed to trigger a VACUUM in any one table. The default is `50`.
    #[serde(rename = "autovacuum_vacuum_threshold", skip_serializing_if = "Option::is_none")]
    pub autovacuum_vacuum_threshold: Option<u32>,
    /// Specifies the minimum delay between autovacuum runs on any given database. The delay is measured in seconds. The default is `60`.
    #[serde(rename = "autovacuum_naptime", skip_serializing_if = "Option::is_none")]
    pub autovacuum_naptime: Option<u32>,
    /// Specifies a fraction of the table size to add to autovacuum_vacuum_threshold when deciding whether to trigger a VACUUM (e.g. `0.2` for 20% of the table size). The default is `0.2`.
    #[serde(rename = "autovacuum_vacuum_scale_factor", skip_serializing_if = "Option::is_none")]
    pub autovacuum_vacuum_scale_factor: Option<f64>,
    /// Specifies the cost delay value that will be used in automatic VACUUM operations. If `-1` is specified, the regular vacuum_cost_delay value will be used. The default is `2` (upstream default).
    #[serde(rename = "autovacuum_vacuum_cost_delay", skip_serializing_if = "Option::is_none")]
    pub autovacuum_vacuum_cost_delay: Option<i8>,
    /// Specifies a fraction of the table size to add to autovacuum_analyze_threshold when deciding whether to trigger an ANALYZE (e.g. `0.2` for 20% of the table size). The default is `0.2`.
    #[serde(rename = "autovacuum_analyze_scale_factor", skip_serializing_if = "Option::is_none")]
    pub autovacuum_analyze_scale_factor: Option<f64>,
    /// Specifies the minimum number of inserted, updated or deleted tuples needed to trigger an ANALYZE in any one table. The default is `50`.
    #[serde(rename = "autovacuum_analyze_threshold", skip_serializing_if = "Option::is_none")]
    pub autovacuum_analyze_threshold: Option<u32>,
    /// Specifies the maximum age (in transactions) that a table's pg_class.relfrozenxid field can attain before a VACUUM operation is forced to prevent transaction ID wraparound within the table. The system launches autovacuum processes to prevent wraparound even when autovacuum is otherwise disabled. Changing this parameter causes a service restart.
    #[serde(rename = "autovacuum_freeze_max_age", skip_serializing_if = "Option::is_none")]
    pub autovacuum_freeze_max_age: Option<u32>,
}

impl AutovacuumSettings {
    pub fn new() -> AutovacuumSettings {
        AutovacuumSettings {
            log_autovacuum_min_duration: None,
            autovacuum_vacuum_cost_limit: None,
            autovacuum_max_workers: None,
            autovacuum_vacuum_threshold: None,
            autovacuum_naptime: None,
            autovacuum_vacuum_scale_factor: None,
            autovacuum_vacuum_cost_delay: None,
            autovacuum_analyze_scale_factor: None,
            autovacuum_analyze_threshold: None,
            autovacuum_freeze_max_age: None,
        }
    }
}

