/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateKmsKeyResponse {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "revision")]
    pub revision: Box<models::RevisionStamp>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "multi-zone")]
    pub multi_zone: bool,
    #[serde(rename = "source")]
    pub source: Source,
    #[serde(rename = "usage")]
    pub usage: String,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "origin-zone")]
    pub origin_zone: String,
    #[serde(rename = "created-at")]
    pub created_at: String,
}

impl CreateKmsKeyResponse {
    pub fn new(description: String, revision: models::RevisionStamp, name: String, multi_zone: bool, source: Source, usage: String, status: Status, id: uuid::Uuid, origin_zone: String, created_at: String) -> CreateKmsKeyResponse {
        CreateKmsKeyResponse {
            description,
            revision: Box::new(revision),
            name,
            multi_zone,
            source,
            usage,
            status,
            id,
            origin_zone,
            created_at,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "exoscale-kms")]
    ExoscaleKms,
}

impl Default for Source {
    fn default() -> Source {
        Self::ExoscaleKms
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "pending-deletion")]
    PendingDeletion,
}

impl Default for Status {
    fn default() -> Status {
        Self::Enabled
    }
}

