/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDbaasClickhouseUserRequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// ClickHouse roles to grant to the user
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Vec<models::DbaasClickhouseUserRoleInput>>,
}

impl CreateDbaasClickhouseUserRequest {
    pub fn new(username: String) -> CreateDbaasClickhouseUserRequest {
        CreateDbaasClickhouseUserRequest {
            username,
            password: None,
            roles: None,
        }
    }
}

