/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDbaasPostgresUserRequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "allow-replication", skip_serializing_if = "Option::is_none")]
    pub allow_replication: Option<bool>,
}

impl CreateDbaasPostgresUserRequest {
    pub fn new(username: String) -> CreateDbaasPostgresUserRequest {
        CreateDbaasPostgresUserRequest {
            username,
            allow_replication: None,
        }
    }
}

