/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSksClusterRequest {
    /// Cluster description
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<std::collections::HashMap<String, String>>,
    /// Cluster CNI
    #[serde(rename = "cni", skip_serializing_if = "Option::is_none")]
    pub cni: Option<Cni>,
    /// Enable auto upgrade of the control plane to the latest patch version available
    #[serde(rename = "auto-upgrade", skip_serializing_if = "Option::is_none")]
    pub auto_upgrade: Option<bool>,
    #[serde(rename = "networking", skip_serializing_if = "Option::is_none")]
    pub networking: Option<Box<models::Networking>>,
    #[serde(rename = "oidc", skip_serializing_if = "Option::is_none")]
    pub oidc: Option<Box<models::SksOidc>>,
    /// Cluster name
    #[serde(rename = "name")]
    pub name: String,
    /// Creates an ad-hoc security group based on the choice of the selected CNI
    #[serde(rename = "create-default-security-group", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub create_default_security_group: Option<Option<bool>>,
    /// Indicates whether to deploy the Kubernetes network proxy. When unspecified, defaults to `true` unless Cilium CNI is selected
    #[serde(rename = "enable-kube-proxy", skip_serializing_if = "Option::is_none")]
    pub enable_kube_proxy: Option<bool>,
    /// Cluster service level
    #[serde(rename = "level")]
    pub level: Level,
    /// A list of Kubernetes-only Alpha features to enable for API server component
    #[serde(rename = "feature-gates", skip_serializing_if = "Option::is_none")]
    pub feature_gates: Option<Vec<String>>,
    /// Cluster addons
    #[serde(rename = "addons", skip_serializing_if = "Option::is_none")]
    pub addons: Option<std::collections::HashSet<Addons>>,
    /// Control plane Kubernetes version
    #[serde(rename = "version")]
    pub version: String,
}

impl CreateSksClusterRequest {
    pub fn new(name: String, level: Level, version: String) -> CreateSksClusterRequest {
        CreateSksClusterRequest {
            description: None,
            labels: None,
            cni: None,
            auto_upgrade: None,
            networking: None,
            oidc: None,
            name,
            create_default_security_group: None,
            enable_kube_proxy: None,
            level,
            feature_gates: None,
            addons: None,
            version,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Cni {
    #[serde(rename = "calico")]
    Calico,
    #[serde(rename = "cilium")]
    Cilium,
}

impl Default for Cni {
    fn default() -> Cni {
        Self::Calico
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Level {
    #[serde(rename = "starter")]
    Starter,
    #[serde(rename = "pro")]
    Pro,
}

impl Default for Level {
    fn default() -> Level {
        Self::Starter
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Addons {
    #[serde(rename = "exoscale-cloud-controller")]
    ExoscaleCloudController,
    #[serde(rename = "exoscale-container-storage-interface")]
    ExoscaleContainerStorageInterface,
    #[serde(rename = "metrics-server")]
    MetricsServer,
}

impl Default for Addons {
    fn default() -> Addons {
        Self::ExoscaleCloudController
    }
}

