/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */
use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDbaasServiceGrafanaRequest {
    #[serde(rename = "maintenance", skip_serializing_if = "Option::is_none")]
    pub maintenance: Option<Box<models::UpdateDbaasServiceMysqlRequestMaintenance>>,
    /// Subscription plan
    #[serde(rename = "plan")]
    pub plan: String,
    /// Service is protected against termination and powering off
    #[serde(
        rename = "termination-protection",
        skip_serializing_if = "Option::is_none"
    )]
    pub termination_protection: Option<bool>,
    #[serde(rename = "fork-from-service", skip_serializing_if = "Option::is_none")]
    pub fork_from_service: Option<String>,
    #[serde(rename = "grafana-settings", skip_serializing_if = "Option::is_none")]
    pub grafana_settings: Option<Box<models::JsonSchemaGrafana>>,
    /// Allowed CIDR address blocks for incoming connections
    #[serde(rename = "ip-filter", skip_serializing_if = "Option::is_none")]
    pub ip_filter: Option<Vec<String>>,
}

impl CreateDbaasServiceGrafanaRequest {
    pub fn new(plan: String) -> CreateDbaasServiceGrafanaRequest {
        CreateDbaasServiceGrafanaRequest {
            maintenance: None,
            plan,
            termination_protection: None,
            fork_from_service: None,
            grafana_settings: None,
            ip_filter: None,
        }
    }
}
