/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasValkeyUser {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "access-control", skip_serializing_if = "Option::is_none")]
    pub access_control: Option<Box<models::DbaasValkeyUserAccessControl>>,
}

impl DbaasValkeyUser {
    pub fn new(username: String) -> DbaasValkeyUser {
        DbaasValkeyUser {
            username,
            r#type: None,
            access_control: None,
        }
    }
}

