/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasEndpointPrometheusPayloadSettings {
    /// Prometheus basic authentication password
    #[serde(rename = "basic-auth-password", skip_serializing_if = "Option::is_none")]
    pub basic_auth_password: Option<String>,
    /// Prometheus basic authentication username
    #[serde(rename = "basic-auth-username", skip_serializing_if = "Option::is_none")]
    pub basic_auth_username: Option<String>,
}

impl DbaasEndpointPrometheusPayloadSettings {
    pub fn new() -> DbaasEndpointPrometheusPayloadSettings {
        DbaasEndpointPrometheusPayloadSettings {
            basic_auth_password: None,
            basic_auth_username: None,
        }
    }
}

