/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasIntegrationSettingsDatadog {
    /// Database monitoring: view query metrics, explain plans, and execution details. Correlate queries with host metrics.
    #[serde(rename = "datadog-dbm-enabled", skip_serializing_if = "Option::is_none")]
    pub datadog_dbm_enabled: Option<bool>,
    /// Integrate PgBouncer with Datadog to track connection pool metrics and monitor application traffic.
    #[serde(rename = "datadog-pgbouncer-enabled", skip_serializing_if = "Option::is_none")]
    pub datadog_pgbouncer_enabled: Option<bool>,
}

impl DbaasIntegrationSettingsDatadog {
    pub fn new() -> DbaasIntegrationSettingsDatadog {
        DbaasIntegrationSettingsDatadog {
            datadog_dbm_enabled: None,
            datadog_pgbouncer_enabled: None,
        }
    }
}

