/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasClickhouseGrantedRole {
    /// Granted role name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    #[serde(rename = "is-default", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    #[serde(rename = "with-admin-option", skip_serializing_if = "Option::is_none")]
    pub with_admin_option: Option<bool>,
}

impl DbaasClickhouseGrantedRole {
    pub fn new(name: String) -> DbaasClickhouseGrantedRole {
        DbaasClickhouseGrantedRole {
            name,
            uuid: None,
            is_default: None,
            with_admin_option: None,
        }
    }
}

