/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasServiceMysqlPrometheusUri {
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<u64>,
}

impl DbaasServiceMysqlPrometheusUri {
    /// Prometheus integration URI
    pub fn new() -> DbaasServiceMysqlPrometheusUri {
        DbaasServiceMysqlPrometheusUri {
            host: None,
            port: None,
        }
    }
}

