/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasClickhouseRolePrivilege {
    #[serde(rename = "name")]
    pub name: String,
    /// Database
    #[serde(rename = "database", skip_serializing_if = "Option::is_none")]
    pub database: Option<String>,
    /// Table
    #[serde(rename = "table", skip_serializing_if = "Option::is_none")]
    pub table: Option<String>,
    #[serde(rename = "grant-option", skip_serializing_if = "Option::is_none")]
    pub grant_option: Option<bool>,
    /// Column
    #[serde(rename = "column", skip_serializing_if = "Option::is_none")]
    pub column: Option<String>,
    #[serde(rename = "is-partial-revoke", skip_serializing_if = "Option::is_none")]
    pub is_partial_revoke: Option<bool>,
}

impl DbaasClickhouseRolePrivilege {
    pub fn new(name: String) -> DbaasClickhouseRolePrivilege {
        DbaasClickhouseRolePrivilege {
            name,
            database: None,
            table: None,
            grant_option: None,
            column: None,
            is_partial_revoke: None,
        }
    }
}

