/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasClickhouseRole {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    #[serde(rename = "privileges", skip_serializing_if = "Option::is_none")]
    pub privileges: Option<Vec<models::DbaasClickhouseRolePrivilege>>,
    #[serde(rename = "granted-roles", skip_serializing_if = "Option::is_none")]
    pub granted_roles: Option<Vec<models::DbaasClickhouseGrantedRole>>,
}

impl DbaasClickhouseRole {
    pub fn new(name: String) -> DbaasClickhouseRole {
        DbaasClickhouseRole {
            name,
            uuid: None,
            privileges: None,
            granted_roles: None,
        }
    }
}

