/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasKafkaAcls {
    #[serde(rename = "topic-acl", skip_serializing_if = "Option::is_none")]
    pub topic_acl: Option<Vec<models::DbaasKafkaTopicAclEntry>>,
    #[serde(rename = "schema-registry-acl", skip_serializing_if = "Option::is_none")]
    pub schema_registry_acl: Option<Vec<models::DbaasKafkaSchemaRegistryAclEntry>>,
}

impl DbaasKafkaAcls {
    pub fn new() -> DbaasKafkaAcls {
        DbaasKafkaAcls {
            topic_acl: None,
            schema_registry_acl: None,
        }
    }
}

