/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasServiceNotification {
    /// Notification level
    #[serde(rename = "level")]
    pub level: Level,
    /// Human notification message
    #[serde(rename = "message")]
    pub message: String,
    /// Notification type
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Notification type
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl DbaasServiceNotification {
    /// Service notifications
    pub fn new(level: Level, message: String, r#type: Type, metadata: serde_json::Value) -> DbaasServiceNotification {
        DbaasServiceNotification {
            level,
            message,
            r#type,
            metadata,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Level {
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "notice")]
    Notice,
}

impl Default for Level {
    fn default() -> Level {
        Self::Warning
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "service_powered_off_removal")]
    ServicePoweredOffRemoval,
    #[serde(rename = "service_end_of_life")]
    ServiceEndOfLife,
}

impl Default for Type {
    fn default() -> Type {
        Self::ServicePoweredOffRemoval
    }
}

