/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasServiceKafkaAuthenticationMethods {
    /// Whether certificate/SSL authentication is enabled
    #[serde(rename = "certificate", skip_serializing_if = "Option::is_none")]
    pub certificate: Option<bool>,
    /// Whether SASL authentication is enabled
    #[serde(rename = "sasl", skip_serializing_if = "Option::is_none")]
    pub sasl: Option<bool>,
}

impl DbaasServiceKafkaAuthenticationMethods {
    /// Kafka authentication methods
    pub fn new() -> DbaasServiceKafkaAuthenticationMethods {
        DbaasServiceKafkaAuthenticationMethods {
            certificate: None,
            sasl: None,
        }
    }
}

