/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbaasExternalIntegration {
    /// Description of the integration
    #[serde(rename = "description")]
    pub description: String,
    /// External destination endpoint name
    #[serde(rename = "dest-endpoint-name", skip_serializing_if = "Option::is_none")]
    pub dest_endpoint_name: Option<String>,
    /// External destination endpoint id
    #[serde(rename = "dest-endpoint-id", skip_serializing_if = "Option::is_none")]
    pub dest_endpoint_id: Option<String>,
    /// Endpoint integration UUID
    #[serde(rename = "integration-id", skip_serializing_if = "Option::is_none")]
    pub integration_id: Option<uuid::Uuid>,
    /// Integration status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// DBaaS source service name
    #[serde(rename = "source-service-name")]
    pub source_service_name: String,
    #[serde(rename = "source-service-type")]
    pub source_service_type: String,
    #[serde(rename = "type")]
    pub r#type: models::EnumExternalEndpointTypes,
}

impl DbaasExternalIntegration {
    /// Integrations with other services
    pub fn new(description: String, source_service_name: String, source_service_type: String, r#type: models::EnumExternalEndpointTypes) -> DbaasExternalIntegration {
        DbaasExternalIntegration {
            description,
            dest_endpoint_name: None,
            dest_endpoint_id: None,
            integration_id: None,
            status: None,
            source_service_name,
            source_service_type,
            r#type,
        }
    }
}

