/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnumPgPoolMode {
    #[serde(rename = "transaction")]
    Transaction,
    #[serde(rename = "statement")]
    Statement,
    #[serde(rename = "session")]
    Session,

}

impl std::fmt::Display for EnumPgPoolMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Transaction => write!(f, "transaction"),
            Self::Statement => write!(f, "statement"),
            Self::Session => write!(f, "session"),
        }
    }
}

impl Default for EnumPgPoolMode {
    fn default() -> EnumPgPoolMode {
        Self::Transaction
    }
}

