/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnumServiceState {
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "rebuilding")]
    Rebuilding,
    #[serde(rename = "rebalancing")]
    Rebalancing,
    #[serde(rename = "poweroff")]
    Poweroff,

}

impl std::fmt::Display for EnumServiceState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Running => write!(f, "running"),
            Self::Rebuilding => write!(f, "rebuilding"),
            Self::Rebalancing => write!(f, "rebalancing"),
            Self::Poweroff => write!(f, "poweroff"),
        }
    }
}

impl Default for EnumServiceState {
    fn default() -> EnumServiceState {
        Self::Running
    }
}

