/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnumMysqlAuthenticationPlugin {
    #[serde(rename = "caching_sha2_password")]
    CachingSha2Password,
    #[serde(rename = "mysql_native_password")]
    MysqlNativePassword,

}

impl std::fmt::Display for EnumMysqlAuthenticationPlugin {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CachingSha2Password => write!(f, "caching_sha2_password"),
            Self::MysqlNativePassword => write!(f, "mysql_native_password"),
        }
    }
}

impl Default for EnumMysqlAuthenticationPlugin {
    fn default() -> EnumMysqlAuthenticationPlugin {
        Self::CachingSha2Password
    }
}

