/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// An absolute or relative URI reference pointing to human-readable documentation concerning the specific problem type encountered.
    #[serde(rename = "type")]
    pub r#type: String,
    /// A brief summary defining the class of failure, optimal for quick user interface groupings.
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "status")]
    pub status: u16,
    /// A highly contextual, readable explanation breaking down explicitly what triggered this error scenario.
    #[serde(rename = "detail")]
    pub detail: String,
}

impl ErrorResponse {
    /// RFC 9457 Problem Details error response
    pub fn new(r#type: String, title: String, status: u16, detail: String) -> ErrorResponse {
        ErrorResponse {
            r#type,
            title,
            status,
            detail,
        }
    }
}

