/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// Event : A notable Mutation Event which happened on the infrastructure

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    /// Operation unique identifier
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// Operation targeted zone
    #[serde(rename = "zone", skip_serializing_if = "Option::is_none")]
    pub zone: Option<String>,
    /// Configuration IP address
    #[serde(rename = "remote-addr", skip_serializing_if = "Option::is_none")]
    pub remote_addr: Option<String>,
    /// Query string parameters (free form map)
    #[serde(rename = "get-params", skip_serializing_if = "Option::is_none")]
    pub get_params: Option<serde_json::Value>,
    /// Body parameters (free form map)
    #[serde(rename = "body-params", skip_serializing_if = "Option::is_none")]
    pub body_params: Option<serde_json::Value>,
    /// Operation HTTP status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i64>,
    /// Operation request URI
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// Operation processing time
    #[serde(rename = "elapsed-ms", skip_serializing_if = "Option::is_none")]
    pub elapsed_ms: Option<i64>,
    /// Time at which the event happened, millisecond resolution
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// URI path parameters (free form map)
    #[serde(rename = "path-params", skip_serializing_if = "Option::is_none")]
    pub path_params: Option<serde_json::Value>,
    /// Operation handler name
    #[serde(rename = "handler", skip_serializing_if = "Option::is_none")]
    pub handler: Option<String>,
    /// Operation message
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl Event {
    /// A notable Mutation Event which happened on the infrastructure
    pub fn new() -> Event {
        Event {
            request_id: None,
            zone: None,
            remote_addr: None,
            get_params: None,
            body_params: None,
            status: None,
            uri: None,
            elapsed_ms: None,
            timestamp: None,
            path_params: None,
            handler: None,
            message: None,
        }
    }
}
