/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForbiddenOperationResponse {
    /// Machine-readable forbidden error code
    #[serde(rename = "code")]
    pub code: Code,
    /// Forbidden error message
    #[serde(rename = "error")]
    pub error: String,
}

impl ForbiddenOperationResponse {
    /// Forbidden operation response
    pub fn new(code: Code, error: String) -> ForbiddenOperationResponse {
        ForbiddenOperationResponse {
            code,
            error,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "forbidden_operation")]
    ForbiddenOperation,
}

impl Default for Code {
    fn default() -> Code {
        Self::ForbiddenOperation
    }
}

