/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateDataKeyResponse {
    /// The Base64-encoded raw symmetric data key payload. Expose only securely during active application setups.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "plaintext")]
    pub plaintext: Vec<u8>,
    /// The identical symmetric data key, returned safely wrapped/encrypted using the designated root parent KMS key.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "ciphertext")]
    pub ciphertext: Vec<u8>,
}

impl GenerateDataKeyResponse {
    pub fn new(plaintext: Vec<u8>, ciphertext: Vec<u8>) -> GenerateDataKeyResponse {
        GenerateDataKeyResponse {
            plaintext,
            ciphertext,
        }
    }
}

