/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInferenceEngineHelpResponse {
    #[serde(rename = "parameters")]
    pub parameters: Vec<models::InferenceEngineParameterEntry>,
}

impl GetInferenceEngineHelpResponse {
    /// List of allowed inference-engine parameters
    pub fn new(parameters: Vec<models::InferenceEngineParameterEntry>) -> GetInferenceEngineHelpResponse {
        GetInferenceEngineHelpResponse {
            parameters,
        }
    }
}

