/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizationUsageResponse {
    /// Total GPU count
    #[serde(rename = "gpu", skip_serializing_if = "Option::is_none")]
    pub gpu: Option<u64>,
}

impl GetOrganizationUsageResponse {
    /// GPU usage for an organization
    pub fn new() -> GetOrganizationUsageResponse {
        GetOrganizationUsageResponse {
            gpu: None,
        }
    }
}

