/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetImpactEstimateRequest {
    #[serde(rename = "sku")]
    pub sku: String,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl GetImpactEstimateRequest {
    pub fn new(sku: String) -> GetImpactEstimateRequest {
        GetImpactEstimateRequest {
            sku,
            metadata: None,
        }
    }
}

