/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDeploymentLogsEntry {
    /// Timestamp of the log entry
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    /// Node identifier
    #[serde(rename = "node", skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    /// Log message content
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl GetDeploymentLogsEntry {
    /// A single log entry
    pub fn new() -> GetDeploymentLogsEntry {
        GetDeploymentLogsEntry {
            time: None,
            node: None,
            message: None,
        }
    }
}

