/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDeploymentLogsResponse {
    /// List of log entries
    #[serde(rename = "logs", skip_serializing_if = "Option::is_none")]
    pub logs: Option<Vec<models::GetDeploymentLogsEntry>>,
}

impl GetDeploymentLogsResponse {
    /// Deployment logs
    pub fn new() -> GetDeploymentLogsResponse {
        GetDeploymentLogsResponse {
            logs: None,
        }
    }
}

