/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDeploymentLogsEntry {
    /// Timestamp of the log entry
    #[serde(rename = "time")]
    pub time: String,
    /// Node identifier
    #[serde(rename = "node")]
    pub node: String,
    /// Log message content
    #[serde(rename = "message")]
    pub message: String,
}

impl GetDeploymentLogsEntry {
    /// A single log entry
    pub fn new(time: String, node: String, message: String) -> GetDeploymentLogsEntry {
        GetDeploymentLogsEntry {
            time,
            node,
            message,
        }
    }
}

