/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IamApiKey {
    /// IAM API Key name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// IAM API Key
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// IAM API Key Role ID
    #[serde(rename = "role-id", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<uuid::Uuid>,
}

impl IamApiKey {
    /// IAM API Key
    pub fn new() -> IamApiKey {
        IamApiKey {
            name: None,
            key: None,
            role_id: None,
        }
    }
}

