/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImpactResourceTreeNode {
    #[serde(rename = "impact")]
    pub impact: std::collections::HashMap<String, models::ImpactValueWithUnit>,
    #[serde(rename = "usage")]
    pub usage: Box<models::ImpactValueWithUnit>,
    #[serde(rename = "resources")]
    pub resources: std::collections::HashMap<String, models::ImpactResourceTreeNode>,
}

impl ImpactResourceTreeNode {
    /// Hierarchical breakdown of impact for a given level in the catalog tree
    pub fn new(impact: std::collections::HashMap<String, models::ImpactValueWithUnit>, usage: models::ImpactValueWithUnit, resources: std::collections::HashMap<String, models::ImpactResourceTreeNode>) -> ImpactResourceTreeNode {
        ImpactResourceTreeNode {
            impact,
            usage: Box::new(usage),
            resources,
        }
    }
}

