/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngestMeteringRequest {
    /// UUID identifying this flush; used for idempotent deduplication
    #[serde(rename = "flush-id")]
    pub flush_id: uuid::Uuid,
    /// Map of api-key-uuid to usage entry. Keys are API key UUIDs. Mirrors the router's in-memory accumulator structure directly.
    #[serde(rename = "usage")]
    pub usage: std::collections::HashMap<String, models::ApiKeyUsageEntry>,
    /// Router instance identifier that produced this flush
    #[serde(rename = "router-id")]
    pub router_id: String,
    /// ISO-8601 UTC timestamp when the flush snapshot was created (truncated to minute boundary for bucketing)
    #[serde(rename = "created-at")]
    pub created_at: String,
}

impl IngestMeteringRequest {
    /// Router flush payload: the router's full in-memory usage map with flush identity fields
    pub fn new(flush_id: uuid::Uuid, usage: std::collections::HashMap<String, models::ApiKeyUsageEntry>, router_id: String, created_at: String) -> IngestMeteringRequest {
        IngestMeteringRequest {
            flush_id,
            usage,
            router_id,
            created_at,
        }
    }
}

