/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstancePoolErrorReason {
    /// Error cause
    #[serde(rename = "cause", skip_serializing_if = "Option::is_none")]
    pub cause: Option<String>,
    /// Job ID at the origin of error
    #[serde(rename = "job-id", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<String>,
}

impl InstancePoolErrorReason {
    /// Instance Pool Error Reason
    pub fn new() -> InstancePoolErrorReason {
        InstancePoolErrorReason {
            cause: None,
            job_id: None,
        }
    }
}

