/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonSchemaKafkaConnect {
    /// The total bytes of memory the producer can use to buffer records waiting to be sent to the broker (defaults to 33554432).
    #[serde(rename = "producer_buffer_memory", skip_serializing_if = "Option::is_none")]
    pub producer_buffer_memory: Option<u32>,
    /// The maximum delay in milliseconds between invocations of poll() when using consumer group management (defaults to 300000).
    #[serde(rename = "consumer_max_poll_interval_ms", skip_serializing_if = "Option::is_none")]
    pub consumer_max_poll_interval_ms: Option<u32>,
    /// Specify the default compression type for producers. This configuration accepts the standard compression codecs ('gzip', 'snappy', 'lz4', 'zstd'). It additionally accepts 'none' which is the default and equivalent to no compression.
    #[serde(rename = "producer_compression_type", skip_serializing_if = "Option::is_none")]
    pub producer_compression_type: Option<ProducerCompressionType>,
    /// Defines what client configurations can be overridden by the connector. Default is None
    #[serde(rename = "connector_client_config_override_policy", skip_serializing_if = "Option::is_none")]
    pub connector_client_config_override_policy: Option<ConnectorClientConfigOverridePolicy>,
    /// The interval at which to try committing offsets for tasks (defaults to 60000).
    #[serde(rename = "offset_flush_interval_ms", skip_serializing_if = "Option::is_none")]
    pub offset_flush_interval_ms: Option<u32>,
    /// The maximum delay that is scheduled in order to wait for the return of one or more departed workers before rebalancing and reassigning their connectors and tasks to the group. During this period the connectors and tasks of the departed workers remain unassigned. Defaults to 5 minutes.
    #[serde(rename = "scheduled_rebalance_max_delay_ms", skip_serializing_if = "Option::is_none")]
    pub scheduled_rebalance_max_delay_ms: Option<u32>,
    /// Records are fetched in batches by the consumer, and if the first record batch in the first non-empty partition of the fetch is larger than this value, the record batch will still be returned to ensure that the consumer can make progress. As such, this is not a absolute maximum.
    #[serde(rename = "consumer_fetch_max_bytes", skip_serializing_if = "Option::is_none")]
    pub consumer_fetch_max_bytes: Option<u32>,
    /// Records are fetched in batches by the consumer.If the first record batch in the first non-empty partition of the fetch is larger than this limit, the batch will still be returned to ensure that the consumer can make progress. 
    #[serde(rename = "consumer_max_partition_fetch_bytes", skip_serializing_if = "Option::is_none")]
    pub consumer_max_partition_fetch_bytes: Option<u32>,
    /// Maximum number of milliseconds to wait for records to flush and partition offset data to be committed to offset storage before cancelling the process and restoring the offset data to be committed in a future attempt (defaults to 5000).
    #[serde(rename = "offset_flush_timeout_ms", skip_serializing_if = "Option::is_none")]
    pub offset_flush_timeout_ms: Option<u32>,
    /// What to do when there is no initial offset in Kafka or if the current offset does not exist any more on the server. Default is earliest
    #[serde(rename = "consumer_auto_offset_reset", skip_serializing_if = "Option::is_none")]
    pub consumer_auto_offset_reset: Option<ConsumerAutoOffsetReset>,
    /// This setting will limit the number of record batches the producer will send in a single request to avoid sending huge requests.
    #[serde(rename = "producer_max_request_size", skip_serializing_if = "Option::is_none")]
    pub producer_max_request_size: Option<u32>,
    /// This setting gives the upper bound of the batch size to be sent. If there are fewer than this many bytes accumulated for this partition, the producer will 'linger' for the linger.ms time waiting for more records to show up. A batch size of zero will disable batching entirely (defaults to 16384).
    #[serde(rename = "producer_batch_size", skip_serializing_if = "Option::is_none")]
    pub producer_batch_size: Option<u32>,
    /// The timeout in milliseconds used to detect failures when using Kafka’s group management facilities (defaults to 10000).
    #[serde(rename = "session_timeout_ms", skip_serializing_if = "Option::is_none")]
    pub session_timeout_ms: Option<u32>,
    /// This setting gives the upper bound on the delay for batching: once there is batch.size worth of records for a partition it will be sent immediately regardless of this setting, however if there are fewer than this many bytes accumulated for this partition the producer will 'linger' for the specified time waiting for more records to show up. Defaults to 0.
    #[serde(rename = "producer_linger_ms", skip_serializing_if = "Option::is_none")]
    pub producer_linger_ms: Option<u16>,
    /// Transaction read isolation level. read_uncommitted is the default, but read_committed can be used if consume-exactly-once behavior is desired.
    #[serde(rename = "consumer_isolation_level", skip_serializing_if = "Option::is_none")]
    pub consumer_isolation_level: Option<ConsumerIsolationLevel>,
    /// The maximum number of records returned in a single call to poll() (defaults to 500).
    #[serde(rename = "consumer_max_poll_records", skip_serializing_if = "Option::is_none")]
    pub consumer_max_poll_records: Option<u16>,
}

impl JsonSchemaKafkaConnect {
    pub fn new() -> JsonSchemaKafkaConnect {
        JsonSchemaKafkaConnect {
            producer_buffer_memory: None,
            consumer_max_poll_interval_ms: None,
            producer_compression_type: None,
            connector_client_config_override_policy: None,
            offset_flush_interval_ms: None,
            scheduled_rebalance_max_delay_ms: None,
            consumer_fetch_max_bytes: None,
            consumer_max_partition_fetch_bytes: None,
            offset_flush_timeout_ms: None,
            consumer_auto_offset_reset: None,
            producer_max_request_size: None,
            producer_batch_size: None,
            session_timeout_ms: None,
            producer_linger_ms: None,
            consumer_isolation_level: None,
            consumer_max_poll_records: None,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProducerCompressionType {
    #[serde(rename = "gzip")]
    Gzip,
    #[serde(rename = "snappy")]
    Snappy,
    #[serde(rename = "lz4")]
    Lz4,
    #[serde(rename = "zstd")]
    Zstd,
    #[serde(rename = "none")]
    None,
}

impl Default for ProducerCompressionType {
    fn default() -> ProducerCompressionType {
        Self::Gzip
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConnectorClientConfigOverridePolicy {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "All")]
    All,
}

impl Default for ConnectorClientConfigOverridePolicy {
    fn default() -> ConnectorClientConfigOverridePolicy {
        Self::None
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConsumerAutoOffsetReset {
    #[serde(rename = "earliest")]
    Earliest,
    #[serde(rename = "latest")]
    Latest,
}

impl Default for ConsumerAutoOffsetReset {
    fn default() -> ConsumerAutoOffsetReset {
        Self::Earliest
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConsumerIsolationLevel {
    #[serde(rename = "read_uncommitted")]
    ReadUncommitted,
    #[serde(rename = "read_committed")]
    ReadCommitted,
}

impl Default for ConsumerIsolationLevel {
    fn default() -> ConsumerIsolationLevel {
        Self::ReadUncommitted
    }
}

