/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonSchemaThanos {
    #[serde(rename = "compactor", skip_serializing_if = "Option::is_none")]
    pub compactor: Option<Box<models::ThanosCompactorUserConfig>>,
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::ThanosQueryUserConfig>>,
    #[serde(rename = "query-frontend", skip_serializing_if = "Option::is_none")]
    pub query_frontend: Option<Box<models::ThanosQueryFrontendUserConfig>>,
}

impl JsonSchemaThanos {
    pub fn new() -> JsonSchemaThanos {
        JsonSchemaThanos {
            compactor: None,
            query: None,
            query_frontend: None,
        }
    }
}

