/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyMaterial {
    /// The incremental index tracing internal key rotation cycles for the key material.
    #[serde(rename = "version")]
    pub version: i32,
    /// The UTC date-time indicating when this particular generation of physical cryptographic material was seeded.
    #[serde(rename = "created-at")]
    pub created_at: String,
    /// A boolean flag indicating whether this specific material version was created during an automated system rotation window.
    #[serde(rename = "automatic")]
    pub automatic: bool,
}

impl KeyMaterial {
    pub fn new(version: i32, created_at: String, automatic: bool) -> KeyMaterial {
        KeyMaterial {
            version,
            created_at,
            automatic,
        }
    }
}

