/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSksClusters200Response {
    #[serde(rename = "sks-clusters", skip_serializing_if = "Option::is_none")]
    pub sks_clusters: Option<Vec<models::SksCluster>>,
}

impl ListSksClusters200Response {
    pub fn new() -> ListSksClusters200Response {
        ListSksClusters200Response {
            sks_clusters: None,
        }
    }
}

