/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDbaasServiceTypes200Response {
    #[serde(rename = "dbaas-service-types", skip_serializing_if = "Option::is_none")]
    pub dbaas_service_types: Option<Vec<models::DbaasServiceType>>,
}

impl ListDbaasServiceTypes200Response {
    pub fn new() -> ListDbaasServiceTypes200Response {
        ListDbaasServiceTypes200Response {
            dbaas_service_types: None,
        }
    }
}

