/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListElasticIps200Response {
    #[serde(rename = "elastic-ips", skip_serializing_if = "Option::is_none")]
    pub elastic_ips: Option<Vec<models::ElasticIp>>,
}

impl ListElasticIps200Response {
    pub fn new() -> ListElasticIps200Response {
        ListElasticIps200Response {
            elastic_ips: None,
        }
    }
}

