/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListModelsResponse {
    #[serde(rename = "models", skip_serializing_if = "Option::is_none")]
    pub models: Option<Vec<models::ListModelsResponseEntry>>,
}

impl ListModelsResponse {
    /// AI model list
    pub fn new() -> ListModelsResponse {
        ListModelsResponse {
            models: None,
        }
    }
}

