/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListKmsKeyRotationsResponseEntry {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "rotated-at")]
    pub rotated_at: String,
    #[serde(rename = "automatic")]
    pub automatic: bool,
}

impl ListKmsKeyRotationsResponseEntry {
    pub fn new(version: i32, rotated_at: String, automatic: bool) -> ListKmsKeyRotationsResponseEntry {
        ListKmsKeyRotationsResponseEntry {
            version,
            rotated_at,
            automatic,
        }
    }
}

