/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// ListInstances200ResponseInstancesInner : Instance



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListInstances200ResponseInstancesInner {
    #[serde(rename = "public-ip-assignment", skip_serializing_if = "Option::is_none")]
    pub public_ip_assignment: Option<crate::models::PublicIpAssignment>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
    /// Instance Security Groups
    #[serde(rename = "security-groups", skip_serializing_if = "Option::is_none")]
    pub security_groups: Option<Vec<crate::models::SecurityGroup>>,
    /// Instance name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "instance-type", skip_serializing_if = "Option::is_none")]
    pub instance_type: Option<Box<crate::models::InstanceType>>,
    /// Instance Private Networks
    #[serde(rename = "private-networks", skip_serializing_if = "Option::is_none")]
    pub private_networks: Option<Vec<crate::models::PrivateNetwork>>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<crate::models::Template>>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<crate::models::InstanceState>,
    #[serde(rename = "ssh-key", skip_serializing_if = "Option::is_none")]
    pub ssh_key: Option<Box<crate::models::SshKey>>,
    #[serde(rename = "manager", skip_serializing_if = "Option::is_none")]
    pub manager: Option<Box<crate::models::Manager>>,
    /// Instance IPv6 address
    #[serde(rename = "ipv6-address", skip_serializing_if = "Option::is_none")]
    pub ipv6_address: Option<String>,
    /// Instance ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Instance SSH Keys
    #[serde(rename = "ssh-keys", skip_serializing_if = "Option::is_none")]
    pub ssh_keys: Option<Vec<crate::models::SshKey>>,
    /// Instance creation date
    #[serde(rename = "created-at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Instance public IPv4 address
    #[serde(rename = "public-ip", skip_serializing_if = "Option::is_none")]
    pub public_ip: Option<String>,
}

impl ListInstances200ResponseInstancesInner {
    /// Instance
    pub fn new() -> ListInstances200ResponseInstancesInner {
        ListInstances200ResponseInstancesInner {
            public_ip_assignment: None,
            labels: None,
            security_groups: None,
            name: None,
            instance_type: None,
            private_networks: None,
            template: None,
            state: None,
            ssh_key: None,
            manager: None,
            ipv6_address: None,
            id: None,
            ssh_keys: None,
            created_at: None,
            public_ip: None,
        }
    }
}


