/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAntiAffinityGroups200Response {
    #[serde(rename = "anti-affinity-groups", skip_serializing_if = "Option::is_none")]
    pub anti_affinity_groups: Option<Vec<models::AntiAffinityGroup>>,
}

impl ListAntiAffinityGroups200Response {
    pub fn new() -> ListAntiAffinityGroups200Response {
        ListAntiAffinityGroups200Response {
            anti_affinity_groups: None,
        }
    }
}

