/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDeploymentsResponse {
    #[serde(rename = "deployments")]
    pub deployments: Vec<models::ListDeploymentsResponseEntry>,
}

impl ListDeploymentsResponse {
    /// AI deployment list
    pub fn new(deployments: Vec<models::ListDeploymentsResponseEntry>) -> ListDeploymentsResponse {
        ListDeploymentsResponse {
            deployments,
        }
    }
}

