/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSosBucketsUsage200Response {
    #[serde(rename = "sos-buckets-usage", skip_serializing_if = "Option::is_none")]
    pub sos_buckets_usage: Option<Vec<models::SosBucketUsage>>,
}

impl ListSosBucketsUsage200Response {
    pub fn new() -> ListSosBucketsUsage200Response {
        ListSosBucketsUsage200Response {
            sos_buckets_usage: None,
        }
    }
}

