/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelUsageCounters {
    /// Total completion/output Unit Of Measurement (UOM) across all calls in this flush window (e.g., tokens for LLMs, minutes for TTS, pages for OCR)
    #[serde(rename = "output-uom")]
    pub output_uom: u32,
    /// Total prompt/input Unit Of Measurement (UOM) across all calls in this flush window (e.g., tokens for LLMs, minutes for TTS, pages for OCR)
    #[serde(rename = "input-uom")]
    pub input_uom: u32,
    /// Number of inference calls in this flush window
    #[serde(rename = "call-count")]
    pub call_count: u32,
}

impl ModelUsageCounters {
    /// Accumulated Unit Of Measurement (UOM) counters for one model over a flush window
    pub fn new(output_uom: u32, input_uom: u32, call_count: u32) -> ModelUsageCounters {
        ModelUsageCounters {
            output_uom,
            input_uom,
            call_count,
        }
    }
}

