/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};


#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NvidiaMigProfileA3024gb {
    #[serde(rename = "2g.12gb")]
    Variant2g12gb,
    #[serde(rename = "1g.6gb+me")]
    Variant1g6gbPlusMe,
    #[serde(rename = "1g.6gb")]
    Variant1g6gb,
    #[serde(rename = "2g.12gb+me")]
    Variant2g12gbPlusMe,
    #[serde(rename = "4g.24gb")]
    Variant4g24gb,

}

impl std::fmt::Display for NvidiaMigProfileA3024gb {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant2g12gb => write!(f, "2g.12gb"),
            Self::Variant1g6gbPlusMe => write!(f, "1g.6gb+me"),
            Self::Variant1g6gb => write!(f, "1g.6gb"),
            Self::Variant2g12gbPlusMe => write!(f, "2g.12gb+me"),
            Self::Variant4g24gb => write!(f, "4g.24gb"),
        }
    }
}

impl Default for NvidiaMigProfileA3024gb {
    fn default() -> NvidiaMigProfileA3024gb {
        Self::Variant2g12gb
    }
}

