/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateNetwork {
    /// Private Network description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<std::collections::HashMap<String, String>>,
    /// Private Network name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Private Network start IP address
    #[serde(rename = "start-ip", skip_serializing_if = "Option::is_none")]
    pub start_ip: Option<String>,
    /// Private Network leased IP addresses
    #[serde(rename = "leases", skip_serializing_if = "Option::is_none")]
    pub leases: Option<Vec<models::PrivateNetworkLease>>,
    /// Private Network ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Private Network VXLAN ID
    #[serde(rename = "vni", skip_serializing_if = "Option::is_none")]
    pub vni: Option<u64>,
    /// Private Network netmask
    #[serde(rename = "netmask", skip_serializing_if = "Option::is_none")]
    pub netmask: Option<String>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::PrivateNetworkOptions>>,
    /// Private Network end IP address
    #[serde(rename = "end-ip", skip_serializing_if = "Option::is_none")]
    pub end_ip: Option<String>,
}

impl PrivateNetwork {
    /// Private Network
    pub fn new() -> PrivateNetwork {
        PrivateNetwork {
            description: None,
            labels: None,
            name: None,
            start_ip: None,
            leases: None,
            id: None,
            vni: None,
            netmask: None,
            options: None,
            end_ip: None,
        }
    }
}

