/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReEncryptRequestSource {
    /// The ID of the source key currently protecting the data payload.
    #[serde(rename = "key")]
    pub key: uuid::Uuid,
    /// Optional Base64-encoded encryption context originally appended to the AAD to confirm package validation rules.
    #[serde_as(as = "super::DoubleOption<serde_with::base64::Base64>")]
    #[serde(rename = "encryption-context", default, skip_serializing_if = "Option::is_none")]
    pub encryption_context: Option<Option<Vec<u8>>>,
    /// The Base64-encoded encrypted payload package ready to undergo source-side key decryption.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "ciphertext")]
    pub ciphertext: Vec<u8>,
}

impl ReEncryptRequestSource {
    pub fn new(key: uuid::Uuid, ciphertext: Vec<u8>) -> ReEncryptRequestSource {
        ReEncryptRequestSource {
            key,
            encryption_context: None,
            ciphertext,
        }
    }
}

