/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResetDbaasValkeyUserPasswordRequest {
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl ResetDbaasValkeyUserPasswordRequest {
    pub fn new() -> ResetDbaasValkeyUserPasswordRequest {
        ResetDbaasValkeyUserPasswordRequest {
            password: None,
        }
    }
}

