/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScaleInstancePoolRequest {
    /// Number of managed Instances
    #[serde(rename = "size")]
    pub size: u64,
}

impl ScaleInstancePoolRequest {
    pub fn new(size: u64) -> ScaleInstancePoolRequest {
        ScaleInstancePoolRequest {
            size,
        }
    }
}

