/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScaleDeploymentRequest {
    /// Number of replicas (>=0)
    #[serde(rename = "replicas")]
    pub replicas: u64,
}

impl ScaleDeploymentRequest {
    /// Scale AI deployment
    pub fn new(replicas: u64) -> ScaleDeploymentRequest {
        ScaleDeploymentRequest {
            replicas,
        }
    }
}

