/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleKmsKeyDeletionRequest {
    /// Number of days to wait until deletion is final.
    #[serde(rename = "delay-days", skip_serializing_if = "Option::is_none")]
    pub delay_days: Option<u8>,
}

impl ScheduleKmsKeyDeletionRequest {
    pub fn new() -> ScheduleKmsKeyDeletionRequest {
        ScheduleKmsKeyDeletionRequest {
            delay_days: None,
        }
    }
}

