/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityGroupResource : Security Group



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityGroupResource {
    /// Security Group ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Security Group name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Whether this points to a public security group. This is only valid when in the context of                    a rule addition which uses a public security group as a source or destination.
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<Visibility>,
}

impl SecurityGroupResource {
    /// Security Group
    pub fn new() -> SecurityGroupResource {
        SecurityGroupResource {
            id: None,
            name: None,
            visibility: None,
        }
    }
}

/// Whether this points to a public security group. This is only valid when in the context of                    a rule addition which uses a public security group as a source or destination.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Visibility {
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "public")]
    Public,
}

impl Default for Visibility {
    fn default() -> Visibility {
        Self::Private
    }
}

