/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SksKubeconfigRequest {
    /// Validity in seconds of the Kubeconfig user certificate (default: 30 days)
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<u64>,
    /// User name in the generated Kubeconfig. The certificate present in the Kubeconfig will also have this name set for the CN field.
    #[serde(rename = "user")]
    pub user: String,
    /// List of roles. The certificate present in the Kubeconfig will have these roles set in the Org field.
    #[serde(rename = "groups")]
    pub groups: Vec<String>,
}

impl SksKubeconfigRequest {
    /// Kubeconfig request for a SKS cluster
    pub fn new(user: String, groups: Vec<String>) -> SksKubeconfigRequest {
        SksKubeconfigRequest {
            ttl: None,
            user,
            groups,
        }
    }
}

