/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://openapi-v2.exoscale.com/source.json) * [YAML format](https://openapi-v2.exoscale.com/source.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDbaasServiceOpensearchRequestIndexPatternsInner {
    /// Maximum number of indexes to keep
    #[serde(rename = "max-index-count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_index_count: Option<Option<u64>>,
    /// Deletion sorting algorithm
    #[serde(rename = "sorting-algorithm", skip_serializing_if = "Option::is_none")]
    pub sorting_algorithm: Option<SortingAlgorithm>,
    /// fnmatch pattern
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
}

impl UpdateDbaasServiceOpensearchRequestIndexPatternsInner {
    pub fn new() -> UpdateDbaasServiceOpensearchRequestIndexPatternsInner {
        UpdateDbaasServiceOpensearchRequestIndexPatternsInner {
            max_index_count: None,
            sorting_algorithm: None,
            pattern: None,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SortingAlgorithm {
    #[serde(rename = "alphabetical")]
    Alphabetical,
    #[serde(rename = "creation_date")]
    CreationDate,
}

impl Default for SortingAlgorithm {
    fn default() -> SortingAlgorithm {
        Self::Alphabetical
    }
}

