/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAiApiKeyRequest {
    /// Human-readable name for the AI API key
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Key scope: 'public' for all deployments, or a specific deployment UUID
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

impl UpdateAiApiKeyRequest {
    /// Request to update an AI API key (at least one property required)
    pub fn new() -> UpdateAiApiKeyRequest {
        UpdateAiApiKeyRequest {
            name: None,
            scope: None,
        }
    }
}

