/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSubnetRequest {
    /// Subnet name
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Subnet description
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<std::collections::HashMap<String, String>>,
    /// Subnet CIDR
    #[serde(rename = "ipv4-block", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ipv4_block: Option<Option<String>>,
}

impl UpdateSubnetRequest {
    pub fn new() -> UpdateSubnetRequest {
        UpdateSubnetRequest {
            name: None,
            description: None,
            labels: None,
            ipv4_block: None,
        }
    }
}

