/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSksNodepoolRequest {
    /// Nodepool Anti-affinity Groups
    #[serde(rename = "anti-affinity-groups", skip_serializing_if = "Option::is_none")]
    pub anti_affinity_groups: Option<Vec<models::AntiAffinityGroupRef>>,
    /// Nodepool description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Configures public IP assignment of the Instances with:  * IPv4 (`inet4`) addressing only; * both IPv4 and IPv6 (`dual`) addressing.
    #[serde(rename = "public-ip-assignment", skip_serializing_if = "Option::is_none")]
    pub public_ip_assignment: Option<PublicIpAssignment>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "taints", skip_serializing_if = "Option::is_none")]
    pub taints: Option<std::collections::HashMap<String, models::SksNodepoolTaint>>,
    /// Nodepool Security Groups
    #[serde(rename = "security-groups", skip_serializing_if = "Option::is_none")]
    pub security_groups: Option<Vec<models::SecurityGroupRef>>,
    /// Nodepool name, lowercase only
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "instance-type", skip_serializing_if = "Option::is_none")]
    pub instance_type: Option<Box<models::InstanceTypeRef>>,
    /// Nodepool Private Networks
    #[serde(rename = "private-networks", skip_serializing_if = "Option::is_none")]
    pub private_networks: Option<Vec<models::PrivateNetworkRef>>,
    /// Prefix to apply to managed instances names (default: pool), lowercase only
    #[serde(rename = "instance-prefix", skip_serializing_if = "Option::is_none")]
    pub instance_prefix: Option<String>,
    #[serde(rename = "deploy-target", skip_serializing_if = "Option::is_none")]
    pub deploy_target: Option<Box<models::DeployTargetRef>>,
    /// Nodepool instances disk size in GiB
    #[serde(rename = "disk-size", skip_serializing_if = "Option::is_none")]
    pub disk_size: Option<u64>,
}

impl UpdateSksNodepoolRequest {
    pub fn new() -> UpdateSksNodepoolRequest {
        UpdateSksNodepoolRequest {
            anti_affinity_groups: None,
            description: None,
            public_ip_assignment: None,
            labels: None,
            taints: None,
            security_groups: None,
            name: None,
            instance_type: None,
            private_networks: None,
            instance_prefix: None,
            deploy_target: None,
            disk_size: None,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PublicIpAssignment {
    #[serde(rename = "inet4")]
    Inet4,
    #[serde(rename = "dual")]
    Dual,
}

impl Default for PublicIpAssignment {
    fn default() -> PublicIpAssignment {
        Self::Inet4
    }
}

