/*
 * Exoscale API
 *
 * Infrastructure automation API, allowing programmatic access to all Exoscale products and services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDeploymentRequest {
    #[serde(rename = "inference-engine-version", skip_serializing_if = "Option::is_none")]
    pub inference_engine_version: Option<models::InferenceEngineVersion>,
    /// Deployment name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Optional extra inference engine server CLI args
    #[serde(rename = "inference-engine-parameters", skip_serializing_if = "Option::is_none")]
    pub inference_engine_parameters: Option<Vec<String>>,
}

impl UpdateDeploymentRequest {
    /// Update AI deployment
    pub fn new() -> UpdateDeploymentRequest {
        UpdateDeploymentRequest {
            inference_engine_version: None,
            name: None,
            inference_engine_parameters: None,
        }
    }
}

